### OpenIddict Password Grant - Get Access Token
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=admin@example.com
&password=Admin@123456
&scope=openid profile email roles

###

### Test Protected Endpoint with OpenIddict Token
GET http://localhost:5000/api/admin/dashboard/stats
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

### Test Users List with OpenIddict Token
GET http://localhost:5000/api/admin/users?page=1&pageSize=10
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

### Refresh Token
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token={{$dotenv REFRESH_TOKEN}}

###

### Client Credentials Grant (for server-to-server)
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=admin_web_app
&client_secret=admin_web_secret
&scope=api

###
